# This file was automatically generated by SWIG
package loris;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package loris;
bootstrap loris;
var_loris_init();
package loris;
@EXPORT = qw( );
1;
