# This file was automatically generated by SWIG
package loris_perl;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package loris_perl;
bootstrap loris_perl;
var_loris_perl_init();
package loris_perl;
@EXPORT = qw( );
1;
