# This file was automatically generated by SWIG
package perLoris;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package perLoris;
bootstrap perLoris;
package perLoris;
@EXPORT = qw( );
1;
