// ===========================================================================
//	Filter.C
//
//	Implementation of Loris::Filter, a generic ARMA digital filter.
//
//	Check this out: http://www.cs.york.ac.uk/~fisher/mkfilter/
//	Digital filter designed by mkfilter/mkshape/gencode   A.J. Fisher
//	This web site is the source of the original implementation here, 
//	and it provides a useful tool for configuring Filter objects. Among
//	the many differences between this implementation and the code 
//	generated by mkfilter, the order of the coefficients and delays is
//	reversed.
//
//	-kel 1 Sep 99
//
// ===========================================================================
#include "Filter.h"
//#include "Exception.h"	//	need this if an Exception is thrown in the
							//	constructor for an invalid AR[0] coefficient

Begin_Namespace( Loris )

// ---------------------------------------------------------------------------
//	Filter constructor
// ---------------------------------------------------------------------------
//	Construct by passing in bounds (STL-style) for MA (x) and AR (y) 
//	coefficient arrays (or vectors), and (optionally) gain, which is 
//	applied to the filter input (defaults to 1.). Coefficients are
//	specified and stored in order of increasing delay.
//
//	The zeroeth AR coefficient (corresponding to the output with delay
//	zero, the current output) must always be zero, naturally. Try to be
//	helpful if only non-zero delay AR coefficients have been specified.
//	It may or may not be helpful to try to second guess the client this 
//	way...
//
Filter::Filter( const double * vcx_begin, const double * vcx_end,
				const double * vcy_begin, const double * vcy_end, 
				double gain /* default 1 */) : 
	_xv( vcx_end - vcx_begin, 0. ), 
	_yv( vcy_end - vcy_begin, 0. ),
	_maCoefs( vcx_begin, vcx_end ),
	_arCoefs( vcy_begin, vcy_end ),
	_gain( gain ),
	_idxX(0),
	_idxY(0)
{
	//	the zeroeth AR coefficient must be zero:
	if ( _arCoefs.size() > 0 && _arCoefs[0] != 0. ) 
	{
		//Throw( InvalidObject, "Tried to create a Filter with non-zero AR coefficient at zero delay." );
		_arCoefs.insert( _arCoefs.begin(), 0. );
		//	need grow the corresponding delay line too:
		_yv.insert( _yv.begin(), 0. );
	}
}

// ---------------------------------------------------------------------------
//	sample
// ---------------------------------------------------------------------------
//	Implement recurrence relation. _maCoefs holds the MA coefficients, _arCoefs
//	holds the AR coeffs. The coefficient vectors and delay lines are ordered
//	by increasing age.
//
double
Filter::sample( double input )
{ 
	double output = 0.;
	
	//	moving average:
	_xv[_idxX] = input * _gain;
	
	for ( int i = 0; i < _maCoefs.size() - _idxX; ++i )
		output += _maCoefs[i] * _xv[i+_idxX];
	for ( int i = _maCoefs.size() - _idxX; i < _maCoefs.size(); ++i )
		output += _maCoefs[i] * _xv[i+_idxX-_maCoefs.size()];
		
	if (_idxX == 0)
		_idxX = _maCoefs.size() - 1;
	else
		--_idxX;
		
	//	auto-regressive:
	for ( int j = 0; j < _arCoefs.size() - _idxY; ++j )
		output += _arCoefs[j] * _yv[j+_idxY];
	for ( int j = _arCoefs.size() - _idxY; j < _arCoefs.size(); ++j )
		output += _arCoefs[j] * _yv[j+_idxY-_arCoefs.size()];
		
	_yv[_idxY] = output;
	
	if (_idxY == 0)
		_idxY = _maCoefs.size() - 1;
	else
		--_idxY;
		
	return output;
}

End_Namespace( Loris )
